"""Build the .htaccess redirect block from docs/redirects.md.

Usage:
    python scripts/build_redirects.py            # writes export/htaccess-redirects.txt
    python scripts/build_redirects.py --cutover  # also includes the "Cutover only" rows

Each table row in docs/redirects.md becomes a case-insensitive mod_rewrite 301.
Rows under "Prefix rules" match the path prefix; all others match the exact path
(with or without the trailing slash). For every nested exact path, the flat-slug
variant is emitted too (the old site resolved /contacts/ as well as
/administration/contacts/), unless that flat slug is a live top-level page.

Paste the output into public_html/.htaccess above "# BEGIN WordPress".
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "redirects.md"
OUT = ROOT / "export" / "htaccess-redirects.txt"

# Top-level slugs that are real pages on the new site; never shadow them.
LIVE_TOP_LEVEL = {
    "contact", "history", "juniors", "masters", "mens", "new-players", "news",
    "resources", "uniforms", "womens", "home-preview", "wp-admin", "wp-content",
    "wp-json", "wp-includes",
}


def parse(include_cutover=False):
    """Return a list of dicts: {old, new, why, kind, section}.

    kind is "exact" or "prefix".
    """
    rows, section = [], ""
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
            continue
        if not line.startswith("| /"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        old, new, why = cells[0], cells[1], cells[2] if len(cells) > 2 else ""
        if section == "Cutover only" and not include_cutover:
            continue
        kind = "prefix" if section.startswith("Prefix rules") else "exact"
        rows.append({"old": old, "new": new, "why": why, "kind": kind, "section": section})
    return rows


def expand(rows):
    """Add flat-slug variants of nested exact paths. Returns (old, new, kind) tuples."""
    out, seen = [], set()

    def add(old, new, kind):
        key = (old.lower(), kind)
        if key not in seen:
            seen.add(key)
            out.append((old, new, kind))

    for r in rows:
        add(r["old"], r["new"], r["kind"])
    for r in rows:
        if r["kind"] != "exact" or r["old"].startswith("/wp-content/"):
            continue
        parts = [p for p in r["old"].split("/") if p]
        if len(parts) > 1 and parts[-1] not in LIVE_TOP_LEVEL:
            add(f"/{parts[-1]}/", r["new"], "exact")
    return out


def rule(old, new, kind):
    path = old.lstrip("/")
    if kind == "prefix":
        pattern = "^" + re.escape(path.rstrip("/")) + ("(/.*)?$" if old.endswith("/") else ".*$")
    elif path.endswith("/"):
        pattern = "^" + re.escape(path.rstrip("/")) + "/?$"
    else:
        pattern = "^" + re.escape(path) + "$"
    # re.escape escapes '-' and '/', which Apache regex doesn't need; keep it readable.
    pattern = pattern.replace("\\-", "-").replace("\\/", "/")
    return f"RewriteRule {pattern} {new} [R=301,L,NC]"


def main():
    cutover = "--cutover" in sys.argv
    pairs = expand(parse(include_cutover=cutover))
    lines = [
        "# BEGIN Mentone redirects",
        "# Generated by scripts/build_redirects.py from docs/redirects.md - edit there, not here.",
        "<IfModule mod_rewrite.c>",
        "RewriteEngine On",
    ]
    lines += [rule(*p) for p in pairs]
    lines += ["</IfModule>", "# END Mentone redirects", ""]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{len(pairs)} rules -> {OUT.relative_to(ROOT)}" + (" (incl. cutover rows)" if cutover else ""))


if __name__ == "__main__":
    main()
